services:
  flask:
    build: ./app
    env_file: .env
    container_name: flask_app
    restart: always
    volumes:
      - socket_volume:/mnt/socket

  nginx:
    image: nginx:stable
    container_name: nginx_server
    ports:
      - "5000:5000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - socket_volume:/mnt/socket
      - ./nginx/static:/mnt/static:ro
      - /mnt/media/Downloads/atlas_images:/mnt/media:ro
    depends_on:
      - flask

volumes:
  socket_volume:
